project_id = "lgnqarwehcunsmnbufbv"

[functions.analyze-media]
verify_jwt = true

[functions.get-shared-analysis]
verify_jwt = false

[functions.analyze-url]
verify_jwt = false

[functions.reverse-image-search]
verify_jwt = false
